86 2d bifurcation diagrams
Trinity-Automata-Research/dsmodels pull request #135
Opened 2018-06-06 22:04 UTC by kmclaren-trinity

2018-06-07 18:06 UTC, sfogarty reviewed
Make an issue to restore taking a dspoint into apply. It should work, we just have to add y to ....

2018-06-07 18:08 UTC, sfogarty commented on R/dsmodel.R
> +		    if(!self$has.diverged(startPoint[[1]],startPoint[[2]],rangeMult)){
The inconsistent of [[1]] vs $x is worrisome. What if $x and $y are valid, but in opposite order?

2018-06-07 18:09 UTC, sfogarty commented on R/dsmodel.R
> +		    if(!self$has.diverged(startPoint[[1]],startPoint[[2]],rangeMult)){
Perhaps we should define functions getX and getY? it would refactor a lot of this.

2018-06-07 18:10 UTC, sfogarty reviewed
When did the man files get added? that seems wrong.

2018-06-07 18:12 UTC, kmclaren-trinity commented
I think I accidentally added the man files with a "git add -A".

2018-06-07 23:56 UTC, sfogarty commented on R/dsmodel.R
> +		    if(!self$has.diverged(startPoint[[1]],startPoint[[2]],rangeMult)){
Make an issue for [[1]] vs $x, quoting the above concern.  Get rid of the rd files. Then re-push and I'll accept the pull request.

2018-06-08 00:00 UTC, sfogarty requested changes
Make an issue for [[1]] vs $x, quoting the above concern. Get rid of the rd files. Then re-push and I'll accept the pull request.

2018-06-08 19:32 UTC, kmclaren-trinity commented
Changes implemented?

2018-06-08 19:48 UTC, sfogarty requested changes
Testing a request changes.

2018-06-08 19:53 UTC, sfogarty approved these changes

2018-06-08 19:54 UTC, sfogarty approved these changes

2018-06-08 19:54 UTC, merged