187 break disconts
Trinity-Automata-Research/dsmodels pull request #189
Opened 2019-06-03 17:24 UTC by nsmoker

2019-06-10 21:48 UTC, sfogarty commented
Documentation from breakDisconts.html (sp) should be in the Details part of dscurve.html.

2019-06-10 21:55 UTC, sfogarty requested changes
Documentation from breakDisconts should be moved to the details section of dscurve.

2019-06-11 16:30 UTC, nsmoker commented
> Documentation from breakDisconts should be moved to the details section of dscurve.

Resolved by adding a section on breaking discontinuities to dscurve.

2019-06-11 18:28 UTC, sfogarty approved these changes

2019-06-11 18:28 UTC, merged